# Generated by Django 4.2.7 on 2023-11-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activation_phone_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_phone_active',
            field=models.BooleanField(default=False),
        ),
    ]
